using System.Text;
using ReTex.Core.Assets;

namespace ReTex.Core.Projects;

/// <summary>Emits a config.cpp for a retexture project: new classes inheriting the source classes with new hiddenSelectionsTextures.</summary>
public static class ConfigGenerator
{
    public static string Generate(RetexProject p)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// Generated by ReTex - edit freely; regenerating overwrites this file.");
        sb.AppendLine();

        // requiredAddons: project defaults + each entry's source addon.
        var required = new List<string>(p.RequiredAddons);
        foreach (var e in p.Entries)
            if (e.SourceAddon.Length > 0 && !required.Contains(e.SourceAddon))
                required.Add(e.SourceAddon);

        var patchClass = Sanitize(p.Name) + "_main";
        var weapons = p.Entries.Where(e => e.Category is AssetCategory.Weapon or AssetCategory.Equipment).ToList();
        var vehicles = p.Entries.Where(e => e.Category is AssetCategory.Vehicle or AssetCategory.Unit
                                            or AssetCategory.Prop or AssetCategory.Backpack).ToList();
        var glasses = p.Entries.Where(e => e.Category is AssetCategory.Glasses).ToList();

        // CfgPatches
        sb.AppendLine("class CfgPatches {");
        sb.AppendLine($"    class {patchClass} {{");
        AppendArray(sb, "units[]", vehicles.Select(e => Quote(e.NewClassName)), 8);
        AppendArray(sb, "weapons[]", weapons.Select(e => Quote(e.NewClassName)), 8);
        sb.AppendLine("        requiredVersion = 0.1;");
        AppendArray(sb, "requiredAddons[]", required.Select(Quote), 8);
        sb.AppendLine("    };");
        sb.AppendLine("};");
        sb.AppendLine();

        EmitCfg(sb, "CfgWeapons", weapons, p);
        EmitCfg(sb, "CfgVehicles", vehicles, p);
        EmitCfg(sb, "CfgGlasses", glasses, p);

        return sb.ToString();
    }

    private static void EmitCfg(StringBuilder sb, string cfgName, List<RetexEntry> entries, RetexProject p)
    {
        if (entries.Count == 0) return;

        sb.AppendLine($"class {cfgName} {{");
        // Any class body that declares `class ItemInfo: ItemInfo` (uniform items, and headgear/vest
        // whose copied source body carries an ItemInfo texture override) needs the engine's
        // CfgWeapons-level `class ItemInfo` forward-declared here, or the inheritance errors with
        // "Undefined base class 'ItemInfo'". Cover both: IsUniform (emitted by EmitUniformItem) and
        // copied bodies that contain a `class ItemInfo` declaration.
        if (entries.Any(e => e.IsUniform || e.CopiedBody.Contains("class ItemInfo", StringComparison.OrdinalIgnoreCase)))
            sb.AppendLine("    class ItemInfo;");
        // Forward-declare each distinct base class.
        foreach (var baseClass in entries.Select(e => e.SourceClass).Distinct(StringComparer.OrdinalIgnoreCase))
            sb.AppendLine($"    class {baseClass};");
        sb.AppendLine();

        foreach (var e in entries)
        {
            if (e.IsUniform) { EmitUniformItem(sb, e, p); continue; }
            if (e.IsUniformUnit) { EmitUniformUnit(sb, e, p); continue; }

            sb.AppendLine($"    class {e.NewClassName}: {e.SourceClass} {{");
            // Full scope trio so the variant reliably shows in Arsenal AND Zeus, even if the source
            // chain set a lower scopeArsenal/scopeCurator (matches working hand-made configs).
            sb.AppendLine("        scope = 2;");
            sb.AppendLine("        scopeArsenal = 2;");
            sb.AppendLine("        scopeCurator = 2;");
            if (e.DisplayName.Length > 0)
                sb.AppendLine($"        displayName = {Quote(e.DisplayName)};");

            // A standalone weapon must point baseWeapon at ITSELF; otherwise Arsenal groups it
            // under the original class and hides it. (Uniforms/worn equipment must NOT have it.)
            if (e.Category is AssetCategory.Weapon)
                sb.AppendLine($"        baseWeapon = {Quote(e.NewClassName)};");

            // Declare hiddenSelections explicitly so the textures bind: when we inherit via an
            // external (forward-declared) base, inherited selections aren't always honoured.
            var selNames = e.Selections.Where(s => s.Name.Length > 0)
                .OrderBy(s => s.Index).Select(s => s.Name).ToList();
            if (selNames.Count > 0 && !e.CopiedBody.Contains("hiddenSelections[]", StringComparison.OrdinalIgnoreCase))
                AppendArray(sb, "hiddenSelections[]", selNames.Select(Quote), 8);

            // Material (rvmat) swaps, index-aligned with hiddenSelections. Generator-owned (the
            // source copy was stripped from CopiedBody), so it always points at the project's rvmats.
            EmitMaterials(sb, e, p);

            if (e.CopiedBody.Length > 0)
            {
                // Copied source values (armor, weapon stats, ItemInfo, ...) with the source
                // texture paths repointed at the project's textures wherever they appear.
                // Strip properties this method already emitted above (scope/scopeArsenal/
                // scopeCurator/displayName/baseWeapon) - defensively, in case CopiedBody was
                // captured by an older ReTex version that didn't exclude them, which would
                // otherwise duplicate the member and fail to compile ("Member already defined").
                // Also strip a redundant "model" redeclaration (same reasoning as
                // RetexProjectService.AddRetexture's skip set: re-declaring an unchanged model path
                // in a derived class is a known way to break hiddenSelections/hiddenSelectionsTextures
                // binding, and it's already inherited unchanged, so dropping it is always safe).
                var body = StripDuplicateKeys(e.CopiedBody.TrimEnd('\r', '\n'),
                    "scope", "scopeArsenal", "scopeCurator", "displayName", "baseWeapon", "model");
                foreach (var s in e.Selections)
                    if (s.ProjectTexture.Length > 0 && s.SourceTexture.Length > 0)
                        body = body.Replace(s.SourceTexture, ProjectVirtual(s, p), StringComparison.OrdinalIgnoreCase);

                if (body.Length > 0)
                {
                    sb.AppendLine("        // --- copied from source class (textures repointed to project) ---");
                    sb.AppendLine(body);
                    sb.AppendLine("        // --- end copied ---");
                }
            }
            else
            {
                // No copied values: emit a positional texture override (top-level only).
                var textures = e.Selections.OrderBy(s => s.Index).Select(s => Quote(TextureFor(s, p)));
                AppendArray(sb, "hiddenSelectionsTextures[]", textures, 8);
            }
            sb.AppendLine("    };");
        }
        sb.AppendLine("};");
        sb.AppendLine();
    }

    /// <summary>
    /// Emits a retextured uniform ITEM (CfgWeapons), modeled on working hand-made configs:
    /// inherit the source uniform, override displayName + textures, and (critically) declare
    /// <c>class ItemInfo: ItemInfo</c> so the base uniform's type/containerClass/mass are inherited
    /// (a bare <c>class ItemInfo {}</c> severs that and hides the uniform from Arsenal). The
    /// <c>uniformClass</c> points at our paired clothing unit (or the original unit as a fallback).
    /// No <c>baseWeapon</c> - a uniform with baseWeapon is treated as a weapon variant and won't show.
    /// </summary>
    private static void EmitUniformItem(StringBuilder sb, RetexEntry e, RetexProject p)
    {
        sb.AppendLine($"    class {e.NewClassName}: {e.SourceClass} {{");
        sb.AppendLine("        scope = 2;");
        sb.AppendLine("        scopeArsenal = 2;");
        sb.AppendLine("        scopeCurator = 2;");
        if (e.DisplayName.Length > 0)
            sb.AppendLine($"        displayName = {Quote(e.DisplayName)};");
        EmitSelectionsAndTextures(sb, e, p);
        sb.AppendLine("        class ItemInfo: ItemInfo {");
        // Many uniforms (including CTR Gravis) also declare the texture override inside ItemInfo.
        // If we only override the item's top-level array, this inherited source array can win when
        // the uniform is equipped and silently restore the original texture on the worn model.
        var itemTextures = e.Selections.OrderBy(s => s.Index)
            .Where(s => s.ProjectTexture.Length > 0 || s.SourceTexture.Length > 0).ToList();
        if (itemTextures.Count > 0)
            AppendArray(sb, "hiddenSelectionsTextures[]",
                itemTextures.Select(s => Quote(TextureFor(s, p))), 12);
        if (e.PartnerClass.Length > 0)
            sb.AppendLine($"            uniformClass = {Quote(e.PartnerClass)};");
        sb.AppendLine("        };");
        sb.AppendLine("    };");
    }

    /// <summary>
    /// Emits the paired clothing UNIT (CfgVehicles) for a uniform: inherit the source unit, wear the
    /// new textures, and point <c>uniformClass</c> back at the new item (the reciprocal link Arsenal
    /// relies on).
    /// </summary>
    private static void EmitUniformUnit(StringBuilder sb, RetexEntry e, RetexProject p)
    {
        sb.AppendLine($"    class {e.NewClassName}: {e.SourceClass} {{");
        sb.AppendLine("        scope = 2;");
        sb.AppendLine("        scopeArsenal = 2;");
        sb.AppendLine("        scopeCurator = 2;");
        if (e.DisplayName.Length > 0)
            sb.AppendLine($"        displayName = {Quote(e.DisplayName)};");
        if (e.PartnerClass.Length > 0)
            sb.AppendLine($"        uniformClass = {Quote(e.PartnerClass)};");
        EmitSelectionsAndTextures(sb, e, p);
        sb.AppendLine("    };");
    }

    /// <summary>Emits hiddenSelections[] (named selections) and hiddenSelectionsTextures[] (project
    /// texture where retextured, else the original) in selection order.</summary>
    private static void EmitSelectionsAndTextures(StringBuilder sb, RetexEntry e, RetexProject p)
    {
        var selNames = e.Selections.Where(s => s.Name.Length > 0)
            .OrderBy(s => s.Index).Select(s => s.Name).ToList();
        if (selNames.Count > 0)
            AppendArray(sb, "hiddenSelections[]", selNames.Select(Quote), 8);

        var textured = e.Selections.OrderBy(s => s.Index)
            .Where(s => s.ProjectTexture.Length > 0 || s.SourceTexture.Length > 0).ToList();
        if (textured.Count > 0)
            AppendArray(sb, "hiddenSelectionsTextures[]", textured.Select(s => Quote(TextureFor(s, p))), 8);

        EmitMaterials(sb, e, p);
    }

    /// <summary>Emits hiddenSelectionsMaterials[] index-aligned with hiddenSelections (selections with
    /// a name, in index order). Each element is the project rvmat's virtual path if the selection was
    /// material-swapped, else the original source material, else "". Emitted only when some selection
    /// carries a material - assets without materials produce no line (byte-identical to before).</summary>
    private static void EmitMaterials(StringBuilder sb, RetexEntry e, RetexProject p)
    {
        var sels = e.Selections.Where(s => s.Name.Length > 0).OrderBy(s => s.Index).ToList();
        if (sels.Count == 0 || !sels.Any(s => s.ProjectMaterial.Length > 0 || s.SourceMaterial.Length > 0)) return;
        AppendArray(sb, "hiddenSelectionsMaterials[]", sels.Select(s => Quote(MaterialFor(s, p))), 8);
    }

    /// <summary>Virtual path of a selection's material: the repointed project rvmat if swapped, else the
    /// original source material, else "" (no override for this selection).</summary>
    private static string MaterialFor(RetexSelection s, RetexProject p) =>
        s.ProjectMaterial.Length > 0 ? ProjectVirtual(p, s.ProjectMaterial)
        : s.SourceMaterial;

    /// <summary>Virtual path of a selection's texture: project texture if retextured, else the original.</summary>
    private static string TextureFor(RetexSelection s, RetexProject p) =>
        s.ProjectTexture.Length > 0 ? ProjectVirtual(s, p) : s.SourceTexture;

    /// <summary>The in-game virtual path of a selection's copied project texture.</summary>
    private static string ProjectVirtual(RetexSelection s, RetexProject p) => ProjectVirtual(p, s.ProjectTexture);

    /// <summary>The in-game virtual path of a project-relative texture (e.g. "textures\foo.paa" =>
    /// "\z\myretex\addons\main\textures\foo.paa"), derived from the project's $PBOPREFIX$.</summary>
    public static string ProjectVirtual(RetexProject p, string projectTexture)
    {
        var prefix = p.Prefix.Replace('/', '\\').Trim('\\');
        var rel = projectTexture.Replace('/', '\\').TrimStart('\\');
        return "\\" + prefix + "\\" + rel;
    }

    /// <summary>Removes top-level "key = ...;" lines for the given property names from a copied
    /// class body (case-insensitive, whitespace-tolerant). Leaves nested classes (e.g. ItemInfo)
    /// untouched - they're indented further and never start with one of these bare property names.</summary>
    private static string StripDuplicateKeys(string body, params string[] keys)
    {
        var lines = body.Split('\n');
        var kept = lines.Where(line =>
        {
            var trimmed = line.TrimStart();
            return !keys.Any(k => trimmed.StartsWith(k, StringComparison.OrdinalIgnoreCase)
                && trimmed.Length > k.Length && (trimmed[k.Length] == ' ' || trimmed[k.Length] == '='));
        });
        return string.Join('\n', kept).TrimEnd('\r', '\n');
    }

    private static string Quote(string s) => "\"" + s.Replace("\"", "\"\"") + "\"";

    /// <summary>
    /// Emits an array initializer with one element per line, e.g.
    /// <code>
    ///         units[] =
    ///         {
    ///             "a",
    ///             "b"
    ///         };
    /// </code>
    /// Empty arrays stay inline (<c>{ }</c>). No trailing comma after the last element - Arma's config
    /// parser rejects it. <paramref name="key"/> includes the <c>[]</c> suffix; <paramref name="indent"/>
    /// is the column of the declaration (elements sit one level, 4 spaces, deeper).
    /// </summary>
    private static void AppendArray(StringBuilder sb, string key, IEnumerable<string> items, int indent)
    {
        var list = items.ToList();
        var pad = new string(' ', indent);
        if (list.Count == 0) { sb.AppendLine($"{pad}{key} = {{ }};"); return; }
        var innerPad = new string(' ', indent + 4);
        sb.AppendLine($"{pad}{key} = {{");
        for (int i = 0; i < list.Count; i++)
            sb.AppendLine($"{innerPad}{list[i]}{(i < list.Count - 1 ? "," : "")}");
        sb.AppendLine($"{pad}}};");
    }

    private static string Sanitize(string s)
    {
        var chars = s.Select(c => char.IsLetterOrDigit(c) || c == '_' ? c : '_').ToArray();
        var r = new string(chars);
        return char.IsDigit(r.FirstOrDefault()) ? "_" + r : r;
    }
}
