using System.Text;
using ReTex.Core.Assets;

namespace ReTex.Core.Projects;

/// <summary>Emits a config.cpp for a retexture project: new classes inheriting the source classes with new hiddenSelectionsTextures.</summary>
public static class ConfigGenerator
{
    public static string Generate(RetexProject p)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// Generated by ReTex - edit freely; regenerating overwrites this file.");
        sb.AppendLine();

        // requiredAddons: project defaults + each entry's source addon.
        var required = new List<string>(p.RequiredAddons);
        foreach (var e in p.Entries)
            if (e.SourceAddon.Length > 0 && !required.Contains(e.SourceAddon))
                required.Add(e.SourceAddon);

        var patchClass = Sanitize(p.Name) + "_main";
        var weapons = p.Entries.Where(e => e.Category is AssetCategory.Weapon or AssetCategory.Equipment).ToList();
        var vehicles = p.Entries.Where(e => e.Category is AssetCategory.Vehicle or AssetCategory.Unit
                                            or AssetCategory.Prop or AssetCategory.Backpack).ToList();
        var glasses = p.Entries.Where(e => e.Category is AssetCategory.Glasses).ToList();

        // CfgPatches
        sb.AppendLine("class CfgPatches {");
        sb.AppendLine($"    class {patchClass} {{");
        sb.AppendLine($"        units[] = {{ {Join(vehicles.Select(e => Quote(e.NewClassName)))} }};");
        sb.AppendLine($"        weapons[] = {{ {Join(weapons.Select(e => Quote(e.NewClassName)))} }};");
        sb.AppendLine("        requiredVersion = 0.1;");
        sb.AppendLine($"        requiredAddons[] = {{ {Join(required.Select(Quote))} }};");
        sb.AppendLine("    };");
        sb.AppendLine("};");
        sb.AppendLine();

        EmitCfg(sb, "CfgWeapons", weapons, p);
        EmitCfg(sb, "CfgVehicles", vehicles, p);
        EmitCfg(sb, "CfgGlasses", glasses, p);

        return sb.ToString();
    }

    private static void EmitCfg(StringBuilder sb, string cfgName, List<RetexEntry> entries, RetexProject p)
    {
        if (entries.Count == 0) return;

        sb.AppendLine($"class {cfgName} {{");
        // Forward-declare each distinct base class.
        foreach (var baseClass in entries.Select(e => e.SourceClass).Distinct(StringComparer.OrdinalIgnoreCase))
            sb.AppendLine($"    class {baseClass};");
        sb.AppendLine();

        foreach (var e in entries)
        {
            if (e.IsUniform) { EmitUniformItem(sb, e, p); continue; }
            if (e.IsUniformUnit) { EmitUniformUnit(sb, e, p); continue; }

            sb.AppendLine($"    class {e.NewClassName}: {e.SourceClass} {{");
            // Full scope trio so the variant reliably shows in Arsenal AND Zeus, even if the source
            // chain set a lower scopeArsenal/scopeCurator (matches working hand-made configs).
            sb.AppendLine("        scope = 2;");
            sb.AppendLine("        scopeArsenal = 2;");
            sb.AppendLine("        scopeCurator = 2;");
            if (e.DisplayName.Length > 0)
                sb.AppendLine($"        displayName = {Quote(e.DisplayName)};");

            // A standalone weapon must point baseWeapon at ITSELF; otherwise Arsenal groups it
            // under the original class and hides it. (Uniforms/worn equipment must NOT have it.)
            if (e.Category is AssetCategory.Weapon)
                sb.AppendLine($"        baseWeapon = {Quote(e.NewClassName)};");

            // Declare hiddenSelections explicitly so the textures bind: when we inherit via an
            // external (forward-declared) base, inherited selections aren't always honoured.
            var selNames = e.Selections.Where(s => s.Name.Length > 0)
                .OrderBy(s => s.Index).Select(s => s.Name).ToList();
            if (selNames.Count > 0 && !e.CopiedBody.Contains("hiddenSelections[]", StringComparison.OrdinalIgnoreCase))
                sb.AppendLine($"        hiddenSelections[] = {{ {Join(selNames.Select(Quote))} }};");

            if (e.CopiedBody.Length > 0)
            {
                // Copied source values (armor, weapon stats, ItemInfo, ...) with the source
                // texture paths repointed at the project's textures wherever they appear.
                var body = e.CopiedBody.TrimEnd('\r', '\n');
                foreach (var s in e.Selections)
                    if (s.ProjectTexture.Length > 0 && s.SourceTexture.Length > 0)
                        body = body.Replace(s.SourceTexture, ProjectVirtual(s, p), StringComparison.OrdinalIgnoreCase);

                sb.AppendLine("        // --- copied from source class (textures repointed to project) ---");
                sb.AppendLine(body);
                sb.AppendLine("        // --- end copied ---");
            }
            else
            {
                // No copied values: emit a positional texture override (top-level only).
                var textures = e.Selections.OrderBy(s => s.Index).Select(s => Quote(TextureFor(s, p)));
                sb.AppendLine($"        hiddenSelectionsTextures[] = {{ {Join(textures)} }};");
            }
            sb.AppendLine("    };");
        }
        sb.AppendLine("};");
        sb.AppendLine();
    }

    /// <summary>
    /// Emits a retextured uniform ITEM (CfgWeapons), modeled on working hand-made configs:
    /// inherit the source uniform, override displayName + textures, and (critically) declare
    /// <c>class ItemInfo: ItemInfo</c> so the base uniform's type/containerClass/mass are inherited
    /// (a bare <c>class ItemInfo {}</c> severs that and hides the uniform from Arsenal). The
    /// <c>uniformClass</c> points at our paired clothing unit (or the original unit as a fallback).
    /// No <c>baseWeapon</c> - a uniform with baseWeapon is treated as a weapon variant and won't show.
    /// </summary>
    private static void EmitUniformItem(StringBuilder sb, RetexEntry e, RetexProject p)
    {
        sb.AppendLine($"    class {e.NewClassName}: {e.SourceClass} {{");
        sb.AppendLine("        scope = 2;");
        sb.AppendLine("        scopeArsenal = 2;");
        sb.AppendLine("        scopeCurator = 2;");
        if (e.DisplayName.Length > 0)
            sb.AppendLine($"        displayName = {Quote(e.DisplayName)};");
        EmitSelectionsAndTextures(sb, e, p);
        sb.AppendLine("        class ItemInfo: ItemInfo {");
        if (e.PartnerClass.Length > 0)
            sb.AppendLine($"            uniformClass = {Quote(e.PartnerClass)};");
        sb.AppendLine("        };");
        sb.AppendLine("    };");
    }

    /// <summary>
    /// Emits the paired clothing UNIT (CfgVehicles) for a uniform: inherit the source unit, wear the
    /// new textures, and point <c>uniformClass</c> back at the new item (the reciprocal link Arsenal
    /// relies on).
    /// </summary>
    private static void EmitUniformUnit(StringBuilder sb, RetexEntry e, RetexProject p)
    {
        sb.AppendLine($"    class {e.NewClassName}: {e.SourceClass} {{");
        sb.AppendLine("        scope = 2;");
        sb.AppendLine("        scopeArsenal = 2;");
        sb.AppendLine("        scopeCurator = 2;");
        if (e.DisplayName.Length > 0)
            sb.AppendLine($"        displayName = {Quote(e.DisplayName)};");
        if (e.PartnerClass.Length > 0)
            sb.AppendLine($"        uniformClass = {Quote(e.PartnerClass)};");
        EmitSelectionsAndTextures(sb, e, p);
        sb.AppendLine("    };");
    }

    /// <summary>Emits hiddenSelections[] (named selections) and hiddenSelectionsTextures[] (project
    /// texture where retextured, else the original) in selection order.</summary>
    private static void EmitSelectionsAndTextures(StringBuilder sb, RetexEntry e, RetexProject p)
    {
        var selNames = e.Selections.Where(s => s.Name.Length > 0)
            .OrderBy(s => s.Index).Select(s => s.Name).ToList();
        if (selNames.Count > 0)
            sb.AppendLine($"        hiddenSelections[] = {{ {Join(selNames.Select(Quote))} }};");

        var textured = e.Selections.OrderBy(s => s.Index)
            .Where(s => s.ProjectTexture.Length > 0 || s.SourceTexture.Length > 0).ToList();
        if (textured.Count > 0)
            sb.AppendLine($"        hiddenSelectionsTextures[] = {{ {Join(textured.Select(s => Quote(TextureFor(s, p))))} }};");
    }

    /// <summary>Virtual path of a selection's texture: project texture if retextured, else the original.</summary>
    private static string TextureFor(RetexSelection s, RetexProject p) =>
        s.ProjectTexture.Length > 0 ? ProjectVirtual(s, p) : s.SourceTexture;

    /// <summary>The in-game virtual path of a selection's copied project texture.</summary>
    private static string ProjectVirtual(RetexSelection s, RetexProject p)
    {
        var prefix = p.Prefix.Replace('/', '\\').Trim('\\');
        var rel = s.ProjectTexture.Replace('/', '\\').TrimStart('\\');
        return "\\" + prefix + "\\" + rel;
    }

    private static string Quote(string s) => "\"" + s.Replace("\"", "\"\"") + "\"";
    private static string Join(IEnumerable<string> items) => string.Join(", ", items);

    private static string Sanitize(string s)
    {
        var chars = s.Select(c => char.IsLetterOrDigit(c) || c == '_' ? c : '_').ToArray();
        var r = new string(chars);
        return char.IsDigit(r.FirstOrDefault()) ? "_" + r : r;
    }
}
